### ISSUE TITLE
Build image docker istio/proxyv2

### ISSUE THREAD

**Issue by fajaryanw** [lehrig/kubeflow-ppc64le-notebook-images#3]
Hi, can you share how to build image docker istio-proxyv2 in ppc64le ?
https://hub.docker.com/r/lehrig/istio-proxyv2
I want running kubeflow in ppc64le but now struggle find guide to build docker image istio-proxyv2 v1.3

sorry, maybe the question is out of topic posting here.
Thanks for your help, greatly appreciated :)

**Comment by lehrig** [comment]
For older versions, we simply cloned what was out there in the community. For example, see https://github.com/IBM/charts/blob/master/stable/ibm-istio/ibm_cloud_pak/manifest.yaml.

Otherwise, I'd refer to https://github.com/ppc64le/build-scripts/tree/master/i for getting build scripts. They're quire current when it comes to istio.
